apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hbstlcrfd-go
  janus-idp.io/tekton: hbstlcrfd-go
  backstage.io/kubernetes-id: hbstlcrfd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hbstlcrfd-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
